version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=postgres

  backend:
    image: pikiha52/csi-be:v1.0
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_NAME=csi_db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_PORT=5432
    restart: on-failure
    ports:
      - 8080:8080
    command: sh -c "mkdir -p uploads && ./main"


  frontend:
    image: pikiha52/csi-fe:v1.0
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://backend:8080
